nodeLinker: pnp

# Zero-install configuration
# This makes all dependencies available through git
compressionLevel: mixed

# Ensure PnP (Plug'n'Play) is properly configured
pnpMode: strict

# Enable strict mode checks
enableStrictSettings: true

# Disable PnP inlining to split .pnp.cjs
pnpEnableInlining: false

# Enable ESM loader for better module support
pnpEnableEsmLoader: true
